name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ruby
      - uses: github/setup-licensed@v1
        with:
          version: '4.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/install-dependencies
      - run: licensed status
